default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  host: localhost

development:
  <<: *default
  database: viewing_party_lite_development

test:
  <<: *default
  database: viewing_party_lite_test

production:
  <<: *default
  database: vp-prod-db
  username: <%= ENV.fetch("PROD_DB_USERNAME") %>
  password: <%= ENV.fetch("PROD_DB_PASSWORD") %>
  host: /cloudsql/vp-demo-383902:us-west1:vp-sql-instance
